const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),performance=require('perf_hooks').performance;
const html=fs.readFileSync(require('path').join(__dirname,'index.html'),'utf8');
const release=require('./RELEASE.json'),sha256=s=>require('node:crypto').createHash('sha256').update(s).digest('hex');
assert.equal(sha256(html),release.htmlSha256,'The portable HTML must match the repository source receipt');
assert.equal(sha256(html.replace(release.guiSourceFingerprint,'__FINGERPRINT__')),release.guiSourceFingerprint,'GUI source fingerprint must match');
assert(!/@aws-sdk|\baws-sdk\b|\bimport\s*\(|\brequire\s*\(|\beval\s*\(|sendBeacon\s*\(|RTCPeerConnection|serviceWorker|AKIA[A-Z0-9]{16}|ASIA[A-Z0-9]{16}|appg(?:prj|ver|dep)_/.test(html));
const elements=new Map();
class Element{constructor(tag='div'){this.tag=tag;this.children=[];this.value='';this.dataset={};this.attrs={};this.handlers={};this.hidden=false;this.disabled=false;this._text='';this.checked=false;this.open=false;this.style={setProperty:(k,v)=>{this.style[k]=v}};this.className='';this.classList={toggle:(name,on)=>{const names=this.className.split(' ').filter(x=>x!==name);if(on)names.push(name);this.className=names.join(' ')}};}set textContent(x){this._text=String(x);this.children=[];}get textContent(){return this._text+this.children.map(c=>c.textContent).join(' ');}append(x){this.children.push(x);}replaceChildren(){this.children=[];this._text='';}setAttribute(k,v){this.attrs[k]=v;}addEventListener(k,f){this.handlers[k]=f;}showModal(){this.open=true;}close(){this.open=false;}focus(){}scrollIntoView(){}setPointerCapture(){}getBoundingClientRect(){return {left:0,width:1440}}click(){this.onclick?.();}}
for(const m of html.matchAll(/id="([^"]+)"/g))elements.set(m[1],new Element());
elements.get('scenario').value='500';
const root=new Element();root.dataset.theme='dark';const splitter=new Element();const nodes=[...html.matchAll(/data-node="([^"]+)"/g)].map(m=>{const e=new Element();e.dataset.node=m[1];return e;});
let timers=[],nextTimer=0;
const sandbox={console,Blob,URL,setTimeout:f=>{const id=++nextTimer;timers.push({id,f});return id},clearTimeout:id=>{timers=timers.filter(t=>t.id!==id)},document:{getElementById:id=>elements.get(id)||null,createElement:t=>new Element(t),documentElement:root,querySelector:s=>s==='.splitter'?splitter:null,querySelectorAll:s=>s==='[data-node]'?nodes:[],addEventListener(){}}};
vm.createContext(sandbox);const start=performance.now();vm.runInContext(html.match(/<script>([\s\S]*?)<\/script>/)[1],sandbox);const initialMs=performance.now()-start;
const el=id=>elements.get(id),run=code=>vm.runInContext(code,sandbox),click=id=>el(id).onclick(),flush=()=>{let count=0;while(timers.length){const t=timers.shift();t.f();assert(++count<10000);}};
assert.equal(run('new Set(findings.map(f=>f.account)).size'),58);assert.equal(run('findings.filter(f=>f.type===\'Security Group\').length'),58*180);assert.equal(run('findings.filter(f=>f.type===\'EC2\').length'),58*120);assert.equal(el('findings').children.length,25);const baseTotal=run('findings.length');assert(baseTotal>30000);
run("preset('S3','s3-bpa')");assert(run("filtered.every(f=>f.control==='s3-bpa'&&fixability(f)==='AUTOMATED')"));assert(run('filtered.length')>1000);
run('selectCandidates(filtered.slice(0,1000))');assert.equal(run('selectedIds.size'),1000);click('preview');assert.equal(run('proposal.targets.length'),1000);assert.equal(run('new Set(proposal.targets.map(t=>t.id)).size'),1000);const snapshot=run('JSON.stringify(proposal.targets)');assert(run('Object.isFrozen(proposal.targets)'));el('model').value='Nova 2 Lite — Enhanced — 8.7x';el('model').onchange();assert.equal(run('JSON.stringify(proposal.targets)'),snapshot);assert(!el('decisions').hidden);click('reject');assert.equal(run('lastRun.simulatedWrites'),0);assert.equal(run('lastRun.results.length'),1000);assert(run("lastRun.results.every(r=>r.currentStatus==='NON_COMPLIANT'&&r.simulatedWrites===0)"));assert.match(el('proposal-status').textContent,/Decision consumed/);const runID=run('lastRun.id');click('approve');assert.equal(run('lastRun.id'),runID);assert.equal(run('lastRun.simulatedWrites'),0);
click('reset');run("preset('S3','s3-bpa')");run('selectCandidates(filtered.slice(0,1000))');click('preview');click('approve');assert.equal(run('lastRun.decision'),'APPROVE ONCE');flush();assert.equal(run('lastRun.state'),'VERIFIED');assert.equal(run('lastRun.simulatedWrites'),1000);assert.equal(run('lastRun.verified'),1000);assert.equal(run('lastRun.realWrites'),0);assert(run("lastRun.targets.every(t=>byId.get(t.id).status==='COMPLIANT')"));const writes=run('lastRun.simulatedWrites');click('approve');click('reject');flush();assert.equal(run('lastRun.simulatedWrites'),writes);assert.match(el('timeline').textContent,/Separate SIMULATED provider/);assert.match(el('timeline').textContent,/Separate SIMULATED compliance/);assert.equal(el('timeline').children.length,5);
click('reset');run("preset('S3','s3-bpa')");run('selectCandidates(filtered.slice(0,1000))');el('failure-mode').checked=true;click('preview');click('approve');flush();assert.equal(run('lastRun.state'),'PARTIAL');assert.equal(run('lastRun.blocked'),Math.floor(1000/17));assert.equal(run('lastRun.simulatedWrites'),1000-Math.floor(1000/17));assert(run("lastRun.results.filter(r=>r.outcome==='BLOCKED').every(r=>r.simulatedWrites===0&&byId.get(r.target).status==='NON_COMPLIANT')"));el('outcome-filter').value='BLOCKED';el('outcome-filter').onchange();assert.equal(el('outcomes').children.length,20);assert.match(el('outcome-count').textContent,/58 matching/);click('outcome-next');assert.match(el('outcome-count').textContent,/page 2/);const beforeReplay=run('lastRun.simulatedWrites');click('replay');flush();assert.equal(run('lastRun.simulatedWrites'),beforeReplay);
click('reset');el('failure-mode').checked=false;run("preset('S3','s3-bpa')");run('selectCandidates(filtered.slice(0,3))');click('preview');run("changeFilter('account','LAB-01')");assert.equal(run('proposal'),null);assert.equal(run('selectedIds.size'),0);click('approve');assert.equal(run('lastRun'),null);
run("resetFilters(); selectCandidates(findings.slice(0,30))");assert(run('selectedIds.size')>0);assert.equal(run('new Set([...selectedIds].map(id=>compatibility(byId.get(id)))).size'),1);const other=run("findings.find(f=>eligible(f)&&compatibility(f)!==selectionKey()).id");const oldSize=run('selectedIds.size');run(`toggleSelection(${JSON.stringify(other)},true)`);assert.equal(run('selectedIds.size'),oldSize);
click('preview');run('byId.get(proposal.targets[0].id).revision++');click('approve');assert.equal(run('proposal'),null);assert.equal(run('lastRun'),null);
run("focusFinding(findings.find(f=>f.control==='s3-logging'&&f.status==='NON_COMPLIANT').id)");assert(el('preview').disabled);click('investigate');assert.match(el('reply').textContent,/no automated proposal/);
click('command-open');assert(el('command-dialog').open);el('command-search').value='s3 bpa';el('command-search').oninput();assert.equal(run('commandMatches.length'),1);run('commandMatches[0].action()');assert.equal(el('control').value,'s3-bpa');assert.equal(el('status').value,'NON_COMPLIANT');el('command-search').value='1000';el('command-search').oninput();assert.equal(run('commandMatches.length'),1);run('commandMatches[0].action()');assert.equal(run('selectedIds.size'),1000);el('command-search').value='account';el('command-search').oninput();assert.equal(run('commandMatches.length'),58);
run("changeFilter('search','no-such-demo-record')");assert.equal(run('filtered.length'),0);assert(el('next').disabled);click('reset-filters');click('next');assert.equal(run('page'),2);click('previous');assert.equal(run('page'),1);click('sort-account');assert.equal(run('sortKey'),'account');click('theme');assert.equal(root.dataset.theme,'light');click('theme');assert.equal(root.dataset.theme,'dark');click('inspect');assert(el('inspector').open);click('inspect-close');assert(!el('inspector').open);nodes[2].onclick();assert.match(el('architecture-detail').textContent,/invokes no agent/);
const maxStart=performance.now();run('generate(1000)');const maxMs=performance.now()-maxStart;assert.equal(run('findings.length'),75400);assert.equal(run('new Set(findings.map(f=>f.id)).size'),75400);assert.equal(el('findings').children.length,25);
assert(!/\b(fetch\s*\(|XMLHttpRequest|WebSocket|EventSource|localStorage|sessionStorage)|arn:aws|https?:\/\/(localhost|127\.|10\.|192\.168\.)/.test(html));assert(!/\b\d{12}\b/.test(html));assert(html.includes("connect-src 'none'"));assert.equal([...html.matchAll(/(?:src|href)="https?:[^\"]+/g)].length,1);
for(const label of ['<title>Agentic Operations Lab · MOCK Showcase</title>','Nova Micro — Economy — 1.0x','Nova Lite — Default — 1.7x','Nova 2 Lite — Enhanced — 8.7x','Input Cost Index','SHOWCASE / MOCK'])assert(html.includes(label));
// P1: every changed filter/search resets high pagination; unchanged refresh does not.
const filterCases={search:'s3',account:'LAB-01',resource:'S3',control:'s3-bpa',status:'NON_COMPLIANT',fixability:'AUTOMATED',severity:'HIGH'};
for(const [id,value] of Object.entries(filterCases)){
 click('reset-filters');run('page=8;refresh()');assert.equal(run('page'),8);
 el(id).value=value;run('refresh()');assert.equal(run('page'),1,`${id} changed refresh must reset`);
 assert(run('filtered.length')>25,`${id} must have matching multi-page results`);
 run('page=2;refresh()');assert.equal(run('page'),2,`${id} unchanged refresh preserves page`);
 click('reset-filters');run('page=8;refresh()');el(id).value=value;el(id).handlers.input();
 assert.equal(run('page'),1,`${id} UI input must reset`);
}
click('reset');const retained=run('focused().resource');run("changeFilter('account','LAB-58')");
assert.equal(run('focused().resource'),retained);
assert(el('selection-note').textContent.includes(retained));
assert.match(el('selection-note').textContent,/Select a resource name to change the finding context/);
run('focusFinding(filtered[0].id)');assert(el('selection-note').textContent.includes(run('focused().resource')));
// P1: one empty-state note, five labels and no repeated per-stage empty copy.
click('reset');assert.equal(el('timeline').children.length,5);
assert(el('timeline').children.every(li=>li.children.length===1));
assert.match(el('evidence-empty').textContent,/No run recorded/);assert(!el('evidence-empty').hidden);
click('preview');assert.match(el('evidence-empty').textContent,/Proposal pending/);
assert(el('timeline').children.every(li=>li.children.length===1));
click('reject');assert(el('evidence-empty').hidden);assert.equal(el('timeline').children.length,5);
assert.match(el('timeline').textContent,/SKIPPED: 0 simulated writes/);
const result={release:'v1.2.1',checks:'PASS — actual script in Node VM / minimal DOM, not browser proof',baselineSyntheticResources:baseTotal,accounts:58,maxScenarioResources:75400,pageSize:25,approve1000Writes:1000,reject1000Writes:0,partial1000Blocked:58,replayNoAdditionalWrites:true,immutableSnapshot:true,mixedCapabilitiesExcluded:true,staleTargetGuard:true,filterChangeCancels:true,commandMenu:true,modelDecisionUnchanged:true,sourceSafetyScan:'PASS',p1FilterResetCount:7,unchangedRefreshPreservesPage:true,retainedContextNamesResource:true,resourceSelectionChangesContext:true,conciseEmptyEvidence:true,fiveEvidenceLabelsRetained:true,realWrites:0,modelCalls:0,initialNodeVmMs:Math.round(initialMs),maxScenarioNodeVmMs:Math.round(maxMs),desktopVisual:'NOT VERIFIED BY VM'};
console.log(JSON.stringify(result,null,2));
